apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipeline-run-
spec:
  pipelineRef:
    name: golang-pipeline
  workspaces:
    - name: pipeline-ws
      persistentVolumeClaim:
        claimName: my-volume-claim